{% set version = "1.0.5" %}

package:
  name: theano
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/T/Theano/Theano-{{ version }}.tar.gz
  sha256: 6e9439dd53ba995fcae27bf20626074bfc2fff446899dc5c53cb28c1f9202e89
  patches:

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - six >=1.9.0
    - numpy >=1.9.1
    - scipy >=0.14
    - pygpu >=0.7.0,<0.8

test:
  requires:
    - nose >=1.3.0
    - nose-parameterized >=0.5.0
  imports:
    - theano
    - theano.compile
    - theano.compile.sandbox
    - theano.compile.tests
    - theano.gof
    - theano.gof.tests
    - theano.gpuarray
    - theano.gpuarray.dnn
    - theano.gpuarray.linalg
    - theano.misc
    - theano.sandbox
    - theano.scalar
    - theano.scalar.tests
    - theano.sparse
    - theano.sparse.tests
    - theano.tensor
    - theano.tensor.nnet
    - theano.tensor.nnet.tests
    - theano.tensor.signal
    - theano.tensor.signal.tests
    - theano.tensor.tests
    - theano.tests

about:
  home: http://deeplearning.net/software/theano/
  license: BSD-3-Clause
  summary: Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.
  license_file: LICENSE.txt
  dev_url: https://github.com/Theano/Theano/
  doc_url: http://deeplearning.net/software/theano/

extra:
  recipe-maintainers:
    - abergeron
    - jakirkham
    - ocefpaf
    - ericmjl
