travis:
  secure:
    BINSTAR_TOKEN: UFOAWlX4TrwI4s5eJnhv20VkoKg8lHAxUulISb66QAHni4CIgnmctohb49AssgPhzdkqucsk3iR+MCkBT0cCoMORl+Mv9nsIyGxJdZHFybT5WmPz9ZImVKXnNoA30YFR+oPzU3mBmOxo83W2GJkW6ivNgV29D1V8Heb1MG8ZEeqmKOObo6ThM48Fqt0CgNw2VpcDIB4rVzm0YD6vjs5oTjBfK157jkXtNDW3kspPO3sza2uF70TKn7d7Zl8uDjlk4yze4qP7e3/AmGTluiahBRz420W8L572L1BGIQP9HmTD/3YjfthfT0TiWTPcejnbsLv30KX/IN6SPqS/70Iin6We+AuGIdG37OgaZUZmq3HFHPq2LuOJkYpE5WqxK8KVyi8tTauGn1x1KkEnR5S5/Oyulvr5vZV3kBN1Errx1UyYU4WAHlum9u/JvUkTgRTLkqwXH8Sfjux9+fAdTISJSfuS9S32YjS5GQFSD94SK7fwPsQ6Dl3UHBCg6/EYjKR1YxmYqSbe+ITislIOxtBB9slSrP4YV54+oebnPwWrc9073NONBZEu06/cWgWuQPJt1S4haB7F/UxicRnALKoRw0bzzPw16+NF6XlkAXBH2qDuKUIATbdLi/j1pFhvLV+WT3p3Q+jSsmGq3QxuPvmmDbiDBnLJTPca6l/1WrCmSoI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
